// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using travel_agency_system.Services;

#nullable disable

namespace travel_agency_system.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260518185656_UpdateTransactionsManyToMany")]
    partial class UpdateTransactionsManyToMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PaymentTransactionTravelPackage", b =>
                {
                    b.Property<Guid>("PaymentTransactionsId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PurchasedToursId")
                        .HasColumnType("char(36)");

                    b.HasKey("PaymentTransactionsId", "PurchasedToursId");

                    b.HasIndex("PurchasedToursId");

                    b.ToTable("PaymentTransactionTravelPackage");
                });

            modelBuilder.Entity("travel_agency_system.Models.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PayerId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PayerId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("travel_agency_system.Models.TravelPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Activities")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("TravelPackages");
                });

            modelBuilder.Entity("travel_agency_system.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("RegDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("travel_agency_system.Models.Admin", b =>
                {
                    b.HasBaseType("travel_agency_system.Models.User");

                    b.Property<bool>("CanEditCatalog")
                        .HasColumnType("tinyint(1)");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("travel_agency_system.Models.Customer", b =>
                {
                    b.HasBaseType("travel_agency_system.Models.User");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("Customer");
                });

            modelBuilder.Entity("PaymentTransactionTravelPackage", b =>
                {
                    b.HasOne("travel_agency_system.Models.PaymentTransaction", null)
                        .WithMany()
                        .HasForeignKey("PaymentTransactionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("travel_agency_system.Models.TravelPackage", null)
                        .WithMany()
                        .HasForeignKey("PurchasedToursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("travel_agency_system.Models.PaymentTransaction", b =>
                {
                    b.HasOne("travel_agency_system.Models.Customer", "Payer")
                        .WithMany("Transactions")
                        .HasForeignKey("PayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payer");
                });

            modelBuilder.Entity("travel_agency_system.Models.Customer", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
